#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_types="(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|wip)"
conventional_commit_regex="^${commit_types}(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
   echo "\033[32mSUCCESS: Commit message meets 'Conventional Commit' standards!\033[0m"
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo "ERROR: The commit message does not meet the 'Conventional Commit standard'"
echo "An example of a valid message is: "
echo "  feat(login): add the 'remember me' button"
echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
echo "***********************************************************************"
echo "Here are the  list of message type : ${commit_types}"
echo "  <type>: <subject> max 50 char ex :- fix: invalid request for login api"
echo "  <type(<scope>):> <subject> (Max 50 char) - <scope> is option ex: - fix(user): email address is empty on profile api"
echo "***********************************************************************"

exit 1